# @package _global_
# Local launcher configuration (no SLURM)

defaults:
  - override /hydra/launcher: basic

n_gpus: 1
cpus_per_task: 8
cache_dir: null # Use stable-worldmodel default cache
wandb:
  enabled: false
  config:
    entity: stable-wm
    project: stable-wm
    name: ${output_model_name}
    id: ${subdir}
    resume: allow
    log_model: False
